### PR TITLE
Change color, smaller text changes and make navbar responsive.

### PR DESCRIPTION
**Pull request by CS-Aditya-Rawat**
I changed the color of the text entered in the contact form.

### CODE REVIEW

**Comment by mateahoward** [comment]
hey @CS-Aditya-Rawat this PR has conflicts we need to sort out before we merge. Do you know how to do that? 

If not here is a quick guide:

git checkout main
git pull origin main

git checkout 'your-branch-nam-here' 
git merge main

git commit -m 'your-commit-message'
git push origin 'your-branch-name-here'


After you've done these steps we'll be able to merge with no conflicts :)

**Comment by CS-Aditya-Rawat** [comment]
Thanks for the help. Done👍

**Comment by mateahoward** [comment]
Sorry @CS-Aditya-Rawat but this overrides our changes and removes work others have done so we still cannot merge:

you're giving us this:
image


while we already had this:
image

**Comment by CS-Aditya-Rawat** [comment]
I just follow your above-mentioned steps I think it automatically pulls the changes Now what should I have to do? I should pull it manually and send another PR or something different.

**Pull request closed without merging**
